name: Run Selenium Test Cases

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest  # More reliable cross-browser support
    strategy:
      matrix:
        browser: [chrome, firefox]  # Test across multiple browsers
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java (Temurin 21)
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Set up specific browser (dynamic based on matrix)
        uses: ${{ matrix.browser }}/setup@vlatest  # Official browser setup actions

      - name: Install project dependencies (if using Maven)
        run: mvn install -DskipTests  # Efficient dependency installation

      - name: Run Selenium tests
        run: mvn test

      - name: Upload test reports (optional)
        uses: actions/upload-artifact@v3  # Store test reports for analysis
        if: always()  # Upload reports even on failures
        with:
          name: test-reports
          path: target/surefire-reports/  # Adjust path based on your project structure

