name: Run Selenium Test Cases

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: windows-latest  # Consider using ubuntu-latest for future browser matrix support
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven
      - uses: browser-actions/setup-chrome@latest
      - run: mvn test  # Remove 'mvn clean' for efficiency
